spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/QPOLLA
    username: postgres
    password: 123 #can be changed.
  jpa:
    show-sql: false
    properties:
      hibernate:
        #generate_statistics: true
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
    hibernate:
      ddl-auto: update
springdoc:
  swagger-ui:
    path: /swagger-ui.html
app:
  jwtSecret: qpollaSecretKey
  jwtExpirationMs: 86400000
